// Generated from PDAX page-data.json by generate-openapi.py — do not edit directly.
// Regenerate with: python3 src/lib/anchors/pdax/generate-openapi.py

export const SOURCES_OF_FUNDS = [
    'Compensation',
    'Sale/Income from Property',
    'Business Income',
    'Pension/Benefit from the Government',
    'Gift/Donation',
    'Sale/Income from Investment',
    'Inheritance/Insurance',
    'Others: <Free Text>',
] as const;
export type SourceOfFunds = (typeof SOURCES_OF_FUNDS)[number];

export const FEE_TYPES = ['Sender', 'Beneficiary'] as const;
export type FeeType = (typeof FEE_TYPES)[number];

export const SEX_VALUES = ['Male', 'Female'] as const;
export type Sex = (typeof SEX_VALUES)[number];

export const PURPOSES = [
    'Business Expense/Employee Remittance',
    'Business Transaction',
    'Gift',
    'Loan',
    'Donation of Financial Aid',
    'Investments/Savings',
    'Purchase of Goods',
    'Education and Training',
    'Travel Expense',
    'Family Support',
    'Legal Obligation',
] as const;
export type Purpose = (typeof PURPOSES)[number];

export const RELATIONSHIPS = [
    'Spouse/Partner',
    'Family',
    'Acquaintance',
    'Colleague',
    'Business',
    'Myself',
] as const;
export type RelationshipOfSenderToBeneficiary = (typeof RELATIONSHIPS)[number];

export const FIAT_IN_METHODS = ['grabpay_cashin', 'dragonpay', 'instapay_upay_cashin'] as const;
export type FiatInMethod = (typeof FIAT_IN_METHODS)[number];

export const FIAT_OUT_METHODS = [
    'PAY-TO-ACCOUNT-REAL-TIME',
    'PAY-TO-ACCOUNT-NON-REAL-TIME',
] as const;
export type FiatOutMethod = (typeof FIAT_OUT_METHODS)[number];

export const COUNTRIES = [
    'Algeria',
    'Albania',
    'Antigua and Barbuda',
    'Armenia',
    'Angola',
    'Andorra',
    'Austria',
    'Bahamas',
    'Argentina',
    'Australia',
    'Azerbaijan',
    'Bahrain',
    'Barbados',
    'Bangladesh',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Chad',
    'Chile',
    'Colombia',
    'China',
    'Comoros',
    'Congo',
    'Croatia',
    'Costa Rica',
    'Cyprus',
    'Czech Republic',
    'Djibouti',
    'Denmark',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'East Timor',
    'Egypt',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Fiji',
    'France',
    'Gabon',
    'Gambia',
    'Germany',
    'Greece',
    'Ghana',
    'Grenada',
    'Guatemala',
    'Guinea-Bissau',
    'Guinea',
    'Guyana',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Malta',
    'Marshall Islands',
    'Mauritius',
    'Micronesia',
    'Monaco',
    'Montenegro',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'New Zealand',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'South Africa',
    'Sri Lanka',
    'Suriname',
    'Switzerland',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Trinidad and Tobago',
    'Turkey',
    'Tuvalu',
    'United Kingdom',
    'United Arab Emirates',
    'Uruguay',
    'Uzbekistan',
    'United States',
    'Vatican City',
    'Vietnam',
    'Zambia',
    'Vanuatu',
] as const;
export type Country = (typeof COUNTRIES)[number];

// Cash-in methods with their source wallet and rail mode. Mirrors
// FIAT_IN_METHODS but carries the metadata that the string union
// above can't express on its own.
export interface FiatInMethodInfo {
    method: FiatInMethod;
    sourceWallet: string;
    mode: string;
}
export const FIAT_IN_METHODS_INFO: readonly FiatInMethodInfo[] = [
    { method: 'grabpay_cashin', sourceWallet: 'Grab', mode: 'Debit Pull' },
    { method: 'dragonpay', sourceWallet: 'All dragonpay supported banks', mode: 'Debit Pull' },
    {
        method: 'instapay_upay_cashin',
        sourceWallet: 'All banks and e-wallets with QRPh enabled',
        mode: 'Scan QRPh',
    },
];

// Crypto tokens supported by PDAX, filtered to Stellar network only.
// PDAX supports 47 additional tokens on other networks (Ethereum, Solana, Polygon, etc.) — see openapi.yaml for the full list.
export interface CryptoToken {
    symbol: string;
    network: string;
}
export const STELLAR_TOKENS: readonly CryptoToken[] = [
    { symbol: 'USDCXLM', network: 'Stellar' },
    { symbol: 'XLM', network: 'Stellar' },
];

// Bank codes used by /fiat/withdraw `beneficiary_bank_code`.
// Includes traditional banks and e-wallet rails.
export interface BankInfo {
    code: string;
    name: string;
    entityType: string;
}
export const BANK_CODES: readonly BankInfo[] = [
    { code: 'BAUBPPH', name: 'UnionBank', entityType: 'Bank' },
    { code: 'BAAIBPH', name: 'Al-Amanah Islamic Investment Bank', entityType: 'Bank' },
    { code: 'BAALIPH', name: 'Alipay', entityType: 'Bank' },
    { code: 'BAALLPH', name: 'All Bank', entityType: 'Bank' },
    { code: 'BAAUBPH', name: 'Asia United Bank', entityType: 'Bank' },
    { code: 'BAANZPH', name: 'Australia and New Zealand Bank', entityType: 'Bank' },
    { code: 'BABDOPH', name: 'BDO Unibank', entityType: 'Bank' },
    { code: 'BABDNPH', name: 'BDO Network Bank', entityType: 'Bank' },
    { code: 'BABOTPH', name: 'BPI', entityType: 'Bank' },
    { code: 'BABPIPH', name: 'BPI Direct Banko', entityType: 'Bank' },
    { code: 'BABAKPH', name: 'Bangko Kabayan', entityType: 'Bank' },
    { code: 'BABAMPH', name: 'Banko Mabuhay', entityType: 'Bank' },
    { code: 'BABNSPH', name: 'Bangko Nuestra Se\u00f1ora Del Pilar', entityType: 'Bank' },
    { code: 'BABKBPH', name: 'Bangkok Bank', entityType: 'Bank' },
    { code: 'BABOAPH', name: 'Bank Of America', entityType: 'Bank' },
    { code: 'BABCHPH', name: 'Bank of China', entityType: 'Bank' },
    { code: 'BABOCPH', name: 'Bank of Commerce', entityType: 'Bank' },
    { code: 'BABOFPH', name: 'Bank of Florida', entityType: 'Bank' },
    { code: 'BABOMPH', name: 'Bank of Makati', entityType: 'Bank' },
    { code: 'BACAMPH', name: 'Camalig Bank', entityType: 'Bank' },
    { code: 'BACANPH', name: 'Cantilan Bank', entityType: 'Bank' },
    { code: 'BACABPH', name: 'Card Bank', entityType: 'Bank' },
    { code: 'BACASPH', name: 'Card SME', entityType: 'Bank' },
    { code: 'BACIMPH', name: 'CIMB Bank', entityType: 'Bank' },
    { code: 'BACTBPH', name: 'CTBC Bank', entityType: 'Bank' },
    { code: 'BACLRPH', name: 'Cebuana Lhuillier', entityType: 'Bank' },
    { code: 'BACHBPH', name: 'China Bank', entityType: 'Bank' },
    { code: 'BACBSPH', name: 'China Bank Savings', entityType: 'Bank' },
    { code: 'BACITPH', name: 'Citibank', entityType: 'Bank' },
    { code: 'BACRBPH', name: 'Community Rural Bank of Romblon', entityType: 'Bank' },
    { code: 'BACBBPH', name: 'Country Builders Bank', entityType: 'Bank' },
    { code: 'BADEVPH', name: 'Development Bank of Philippines', entityType: 'Bank' },
    { code: 'BADUNPH', name: 'Dungganon Bank Inc.', entityType: 'Bank' },
    { code: 'BADEBPH', name: 'Deutsche Bank', entityType: 'Bank' },
    { code: 'BADCDPH', name: 'Dumaguete City Development Bank', entityType: 'Bank' },
    { code: 'BAEWBPH', name: 'East West Bank', entityType: 'Bank' },
    { code: 'BAEWRPH', name: 'East West Rural Bank', entityType: 'Bank' },
    { code: 'BAEQSPH', name: 'Equicom', entityType: 'Bank' },
    { code: 'BAFCBPH', name: 'First Consolidated Bank', entityType: 'Bank' },
    { code: 'BAGRBPH', name: 'Guagua Rural Bank', entityType: 'Bank' },
    { code: 'BAGTBPH', name: 'GoTyme', entityType: 'Bank' },
    { code: 'BAHSBPH', name: 'HSBC Savings', entityType: 'Bank' },
    { code: 'BAHSSPH', name: 'HSBC Savings', entityType: 'Bank' },
    { code: 'BAISLPH', name: 'Isla Bank', entityType: 'Bank' },
    { code: 'BAICOPH', name: 'Industrial & Commercial Bank of China', entityType: 'Bank' },
    { code: 'BAIBKPH', name: 'Industrial Bank of Korea', entityType: 'Bank' },
    { code: 'BAINGPH', name: 'ING Bank', entityType: 'Bank' },
    { code: 'BAIVBPH', name: 'Innovative Bank', entityType: 'Bank' },
    { code: 'BAJPMPH', name: 'JPMorgan Chase Bank', entityType: 'Bank' },
    { code: 'BAKEBPH', name: 'KEB Hana Bank', entityType: 'Bank' },
    { code: 'BALABPH', name: 'Landbank', entityType: 'Bank' },
    { code: 'BALSBPH', name: 'Legazpi Savings Bank', entityType: 'Bank' },
    { code: 'BALDBPH', name: 'Luzon Development Bank', entityType: 'Bank' },
    { code: 'BAICBPH', name: 'Mega ICBC', entityType: 'Bank' },
    { code: 'BAMBSPH', name: 'Malayan Bank', entityType: 'Bank' },
    { code: 'BAMAYPH', name: 'Maybank', entityType: 'Bank' },
    { code: 'BAMCCPH', name: 'MCCB', entityType: 'Bank' },
    { code: 'BAMBAPH', name: 'Metrobank', entityType: 'Bank' },
    { code: 'BAMIZPH', name: 'Mizuho Bank', entityType: 'Bank' },
    { code: 'BAMUFPH', name: 'MUFG Bank', entityType: 'Bank' },
    { code: 'BANETPH', name: 'Netbank', entityType: 'Bank' },
    { code: 'BAOMNPH', name: 'Omnipay', entityType: 'Bank' },
    { code: 'BAPBOPH', name: 'PBCom', entityType: 'Bank' },
    { code: 'BAPASPH', name: 'Pacific Ace Savings Bank', entityType: 'Bank' },
    { code: 'BAPRBPH', name: 'Partner Rural Bank', entityType: 'Bank' },
    { code: 'BAPBBPH', name: 'Philippine Business Bank', entityType: 'Bank' },
    { code: 'BAPNBPH', name: 'PNB', entityType: 'Bank' },
    { code: 'BAPBAPH', name: 'PS Bank', entityType: 'Bank' },
    { code: 'BAPTCPH', name: 'PhilTrust Bank', entityType: 'Bank' },
    { code: 'BAPVBPH', name: 'Philippine Veterans Bank', entityType: 'Bank' },
    { code: 'BAPCBPH', name: 'Producers Bank', entityType: 'Bank' },
    { code: 'BAPSBPH', name: 'Producers Savings Bank', entityType: 'Bank' },
    { code: 'BAQBAPH', name: 'Queen City Development Bank', entityType: 'Bank' },
    { code: 'BAQCRPH', name: 'QCRB', entityType: 'Bank' },
    { code: 'BARANPH', name: 'Rang-Ay Bank', entityType: 'Bank' },
    { code: 'BARCBPH', name: 'RCBC', entityType: 'Bank' },
    { code: 'BAROBPH', name: 'Robinsons Bank', entityType: 'Bank' },
    { code: 'BARBOPH', name: 'Rural Bank of Guinobatan (Asenso)', entityType: 'Bank' },
    { code: 'BARBDPH', name: 'Rural Bank of Digos', entityType: 'Bank' },
    { code: 'BARBMPH', name: 'Rural Bank of Montalban', entityType: 'Bank' },
    { code: 'BASECPH', name: 'Security Bank', entityType: 'Bank' },
    { code: 'BASEAPH', name: 'Seabank', entityType: 'Bank' },
    { code: 'BASHBPH', name: 'Shinhan Bank', entityType: 'Bank' },
    { code: 'BASCBPH', name: 'Standard Chartered Bank', entityType: 'Bank' },
    { code: 'BASTAPH', name: 'Starpay', entityType: 'Bank' },
    { code: 'BASBOPH', name: 'Sterling Bank of Asia', entityType: 'Bank' },
    { code: 'BASMBPH', name: 'Sumimoto Mitsui Banking', entityType: 'Bank' },
    { code: 'BASSBPH', name: 'Sun Savings Bank', entityType: 'Bank' },
    { code: 'BATDBPH', name: 'Tonik Digital Bank', entityType: 'Bank' },
    { code: 'BATYBPH', name: 'Tong Yang Savings Bank', entityType: 'Bank' },
    { code: 'BAUCPPH', name: 'UCPB Savings Bank', entityType: 'Bank' },
    { code: 'BAUCCPH', name: 'United Coconut Planters Bank', entityType: 'Bank' },
    { code: 'BAUNOPH', name: 'UNObank', entityType: 'Bank' },
    { code: 'BAUDLPH', name: 'UnionDigital', entityType: 'Bank' },
    { code: 'BAUOVPH', name: 'United Overseas Bank Phils.', entityType: 'Bank' },
    { code: 'BAWEBPH', name: 'Wealth Bank', entityType: 'Bank' },
    { code: 'BAYSBPH', name: 'Yuanta Savings Bank', entityType: 'Bank' },
    { code: 'BAMABPH', name: 'Maya Bank', entityType: 'Bank' },
    { code: 'EWGXCPH', name: 'GCash', entityType: 'Ewallet' },
    { code: 'EWCISPH', name: 'Bayad', entityType: 'Ewallet' },
    { code: 'EWGRAPH', name: 'GrabPay', entityType: 'Ewallet' },
    { code: 'EWLLFPH', name: 'Lulu Money', entityType: 'Ewallet' },
    { code: 'EWPPPH', name: 'PalawanPay', entityType: 'Ewallet' },
    { code: 'EWSPPPH', name: 'ShopeePay', entityType: 'Ewallet' },
    { code: 'EWTACPH', name: 'TayoCash', entityType: 'Ewallet' },
    { code: 'EWUSCPH', name: 'USSC', entityType: 'Ewallet' },
    { code: 'EWJUCPH', name: 'Juan Cash', entityType: 'Ewallet' },
    { code: 'EWPDXPH', name: 'Philippine Digital Asset Exchange', entityType: 'Ewallet' },
    { code: 'EWPAYPH', name: 'Maya Wallet', entityType: 'Ewallet' },
];

// Required and optional identity fields per fiat endpoint, sourced from
// the request-body schemas of /fiat/deposit and /fiat/withdraw. The PDAX
// client's getKycRequirements() returns the union of these two arrays;
// `enumConst` points at the matching value-set exported above so the
// KycForm can render dropdowns without a separate field-to-enum map.
export type IdentityFieldKind = 'string' | 'date' | 'enum';
export type IdentityFieldEnum =
    | 'COUNTRIES'
    | 'BANK_CODES'
    | 'FIAT_IN_METHODS'
    | 'FIAT_OUT_METHODS'
    | 'SOURCES_OF_FUNDS'
    | 'PURPOSES'
    | 'FEE_TYPES'
    | 'SEX_VALUES'
    | 'RELATIONSHIPS';
export interface IdentityFieldSpec {
    name: string;
    required: boolean;
    kind: IdentityFieldKind;
    enumConst?: IdentityFieldEnum;
    description?: string;
}

export const FIAT_DEPOSIT_IDENTITY_FIELDS: readonly IdentityFieldSpec[] = [
    {
        name: 'amount',
        required: true,
        kind: 'string',
        description: 'Amount to be sent to beneficiary',
    },
    { name: 'method', required: true, kind: 'enum', enumConst: 'FIAT_IN_METHODS' },
    {
        name: 'identifier',
        required: true,
        kind: 'string',
        description: 'Unique identifier supplied by client',
    },
    { name: 'sender_first_name', required: true, kind: 'string', description: 'Sender first name' },
    {
        name: 'sender_middle_name',
        required: true,
        kind: 'string',
        description: 'Sender middle name',
    },
    { name: 'sender_last_name', required: true, kind: 'string', description: 'Sender last name' },
    {
        name: 'sender_country_origin',
        required: true,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Where the sender is sending the funds from',
    },
    {
        name: 'sender_address_line_one',
        required: false,
        kind: 'string',
        description: 'Address line 1',
    },
    {
        name: 'sender_address_line_two',
        required: false,
        kind: 'string',
        description: 'Address line 2',
    },
    { name: 'sender_city', required: false, kind: 'string', description: 'City' },
    { name: 'sender_province', required: false, kind: 'string', description: 'Province' },
    { name: 'sender_country', required: false, kind: 'enum', enumConst: 'COUNTRIES' },
    { name: 'sender_zip_code', required: false, kind: 'string', description: 'Zip code' },
    { name: 'sender_phone_number', required: false, kind: 'string', description: 'Phone number' },
    { name: 'sender_nationality', required: false, kind: 'enum', enumConst: 'COUNTRIES' },
    {
        name: 'sender_national_identity_number',
        required: false,
        kind: 'string',
        description: 'Alphanumeric code from national IDs / government IDs',
    },
    {
        name: 'sender_dob',
        required: false,
        kind: 'date',
        description:
            'Date of birth for individuals / Date of Incorporation for businessesmm-dd-yyyy format',
    },
    {
        name: 'sender_place_of_birth',
        required: false,
        kind: 'string',
        description: 'Place of birth for individuals / place of incorporation for businesses',
    },
    {
        name: 'source_of_funds',
        required: true,
        kind: 'enum',
        enumConst: 'SOURCES_OF_FUNDS',
        description: 'Source of funds',
    },
    { name: 'sender_email', required: false, kind: 'string', description: "Sender's email" },
    {
        name: 'beneficiary_first_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary first name',
    },
    {
        name: 'beneficiary_middle_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary middle name',
    },
    {
        name: 'beneficiary_last_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary last name',
    },
    {
        name: 'beneficiary_sex',
        required: false,
        kind: 'enum',
        enumConst: 'SEX_VALUES',
        description: 'Sex of beneficiary',
    },
    {
        name: 'beneficiary_nationality',
        required: false,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Nationality of the beneficiary',
    },
    {
        name: 'beneficiary_dob',
        required: false,
        kind: 'date',
        description: 'Date of birth for individuals / Date of Incorporation for businesses',
    },
    {
        name: 'beneficiary_address_line_one',
        required: false,
        kind: 'string',
        description: 'Beneficiary address line 1',
    },
    {
        name: 'beneficiary_address_line_two',
        required: false,
        kind: 'string',
        description: 'Beneficiary address line 2',
    },
    {
        name: 'beneficiary_barangay',
        required: false,
        kind: 'string',
        description: 'Barangay of beneficiary',
    },
    {
        name: 'beneficiary_city',
        required: false,
        kind: 'string',
        description: 'City of beneficiary',
    },
    {
        name: 'beneficiary_province',
        required: false,
        kind: 'string',
        description: 'Province of beneficiary',
    },
    {
        name: 'beneficiary_country',
        required: false,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Country of beneficiary',
    },
    {
        name: 'beneficiary_zip_code',
        required: false,
        kind: 'string',
        description: 'Zip code of beneficiary',
    },
    {
        name: 'beneficiary_phone_number',
        required: false,
        kind: 'string',
        description: 'Phone number of beneficiary',
    },
    {
        name: 'beneficiary_government_issued_id',
        required: false,
        kind: 'string',
        description: 'Government issued id of beneficiary',
    },
    {
        name: 'purpose',
        required: true,
        kind: 'enum',
        enumConst: 'PURPOSES',
        description: 'Purpose of the transaction',
    },
    {
        name: 'relationship_of_sender_to_beneficiary',
        required: true,
        kind: 'enum',
        enumConst: 'RELATIONSHIPS',
        description: 'Relationship of sender to beneficiary',
    },
    {
        name: 'currency',
        required: true,
        kind: 'string',
        description: 'Currency of the withdrawalPHP',
    },
    {
        name: 'nature_of_business',
        required: false,
        kind: 'string',
        description: 'Nature of business of beneficiary',
    },
];

export const FIAT_WITHDRAW_IDENTITY_FIELDS: readonly IdentityFieldSpec[] = [
    {
        name: 'identifier',
        required: true,
        kind: 'string',
        description: 'Unique identifier supplied by client',
    },
    { name: 'sender_first_name', required: true, kind: 'string', description: 'Sender first name' },
    {
        name: 'sender_middle_name',
        required: true,
        kind: 'string',
        description: 'Sender middle name',
    },
    { name: 'sender_last_name', required: true, kind: 'string', description: 'Sender last name' },
    {
        name: 'sender_country_origin',
        required: true,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Where the sender is sending the funds from',
    },
    {
        name: 'sender_address_line_one',
        required: false,
        kind: 'string',
        description: 'Address line line one',
    },
    {
        name: 'sender_address_line_two',
        required: false,
        kind: 'string',
        description: 'Address line line two',
    },
    { name: 'sender_city', required: false, kind: 'string', description: 'City' },
    { name: 'sender_province', required: false, kind: 'string', description: 'Province' },
    { name: 'sender_country', required: false, kind: 'enum', enumConst: 'COUNTRIES' },
    { name: 'sender_zip_code', required: false, kind: 'string', description: 'Zip code' },
    { name: 'sender_phone_number', required: false, kind: 'string', description: 'Phone number' },
    { name: 'sender_nationality', required: false, kind: 'enum', enumConst: 'COUNTRIES' },
    {
        name: 'sender_national_identity_number',
        required: false,
        kind: 'string',
        description: 'Alphanumeric code from national IDs / government IDs',
    },
    {
        name: 'sender_dob',
        required: false,
        kind: 'date',
        description:
            'Date of birth for individuals / Date of Incorporation for businessesmm-dd-yyyy format',
    },
    {
        name: 'sender_place_of_birth',
        required: false,
        kind: 'string',
        description: 'Place of birth for individuals / place of incorporation for businesses',
    },
    {
        name: 'source_of_funds',
        required: true,
        kind: 'enum',
        enumConst: 'SOURCES_OF_FUNDS',
        description: 'Source of funds',
    },
    { name: 'sender_email', required: false, kind: 'string', description: "Sender's email" },
    {
        name: 'fee_type',
        required: true,
        kind: 'enum',
        enumConst: 'FEE_TYPES',
        description:
            'Fiat out fee to be shouldered either by Sender or Beneficiary, you may opt to choose either option to determine where fees will be debited from',
    },
    {
        name: 'beneficiary_first_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary first name',
    },
    {
        name: 'beneficiary_middle_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary middle name',
    },
    {
        name: 'beneficiary_last_name',
        required: true,
        kind: 'string',
        description: 'Beneficiary last name',
    },
    {
        name: 'beneficiary_sex',
        required: false,
        kind: 'enum',
        enumConst: 'SEX_VALUES',
        description: 'Sex of beneficiary',
    },
    {
        name: 'beneficiary_nationality',
        required: false,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Nationality of the beneficiary',
    },
    {
        name: 'beneficiary_dob',
        required: false,
        kind: 'date',
        description: 'Date of birth for individuals / Date of Incorporation for businesses',
    },
    {
        name: 'beneficiary_bank_code',
        required: true,
        kind: 'enum',
        enumConst: 'BANK_CODES',
        description: 'Bank code to determine which bank the funds will arrive at',
    },
    {
        name: 'beneficiary_account_name',
        required: true,
        kind: 'string',
        description: 'Bank account name of the beneficiary',
    },
    {
        name: 'beneficiary_account_number',
        required: true,
        kind: 'string',
        description: 'Bank account number of the beneficiary',
    },
    {
        name: 'beneficiary_address_line_one',
        required: false,
        kind: 'string',
        description: 'Beneficiary address line 1',
    },
    {
        name: 'beneficiary_address_line_two',
        required: false,
        kind: 'string',
        description: 'Beneficiary address line 2',
    },
    {
        name: 'beneficiary_barangay',
        required: false,
        kind: 'string',
        description: 'Barangay of beneficiary',
    },
    {
        name: 'beneficiary_city',
        required: false,
        kind: 'string',
        description: 'City of beneficiary',
    },
    {
        name: 'beneficiary_province',
        required: false,
        kind: 'string',
        description: 'Province of beneficiary',
    },
    {
        name: 'beneficiary_country',
        required: false,
        kind: 'enum',
        enumConst: 'COUNTRIES',
        description: 'Country of beneficiary',
    },
    {
        name: 'beneficiary_zip_code',
        required: false,
        kind: 'string',
        description: 'Zip code of beneficiary',
    },
    {
        name: 'beneficiary_phone_number',
        required: false,
        kind: 'string',
        description: 'Phone number of beneficiary',
    },
    {
        name: 'beneficiary_government_issued_id',
        required: false,
        kind: 'string',
        description: 'Government issued id of beneficiary',
    },
    {
        name: 'nature_of_business',
        required: false,
        kind: 'string',
        description: 'Nature of business of beneficiary',
    },
    {
        name: 'purpose',
        required: true,
        kind: 'enum',
        enumConst: 'PURPOSES',
        description: 'Purpose of the transaction',
    },
    {
        name: 'relationship_of_sender_to_beneficiary',
        required: true,
        kind: 'enum',
        enumConst: 'RELATIONSHIPS',
        description: 'Relationship of sender to beneficiary',
    },
    {
        name: 'currency',
        required: true,
        kind: 'string',
        description: 'Currency of the withdrawalPHP',
    },
    {
        name: 'amount',
        required: true,
        kind: 'string',
        description: 'Amount to be sent to beneficiary',
    },
    { name: 'method', required: true, kind: 'enum', enumConst: 'FIAT_OUT_METHODS' },
    { name: 'instructions', required: false, kind: 'string', description: 'Other instructions' },
];

// Error codes returned by the PDAX API. Includes global PAP* codes plus
// per-endpoint OT01xxxx codes from Trade / Crypto Out responses, and the
// textual validation codes from /fiat/withdraw ("Missing identifier",
// "Invalid sender_phone_number", etc.). Sorted PAP → OT → textual.
export interface ErrorInfo {
    code: string;
    name: string;
    httpStatus: number | null;
    message: string;
}
export const ERROR_CODES: readonly ErrorInfo[] = [
    { code: 'PAP0400', name: 'BadRequest', httpStatus: 400, message: 'Bad request' },
    { code: 'PAP0401', name: 'Unauthorize', httpStatus: 401, message: 'Unauthorize' },
    {
        code: 'PAP0500',
        name: 'InternalServerError',
        httpStatus: 500,
        message: 'Internal Server Error',
    },
    {
        code: 'PAP0503',
        name: 'ServiceUnavailable',
        httpStatus: 503,
        message: 'Service unavailable',
    },
    { code: 'OT000000', name: '', httpStatus: 500, message: 'Something went wrong' },
    { code: 'OT010000', name: '', httpStatus: 400, message: 'Unauthorized access' },
    { code: 'OT010001', name: '', httpStatus: 400, message: 'Request has been made several times' },
    { code: 'OT010002', name: '', httpStatus: 400, message: 'Failed to acquire database lock' },
    {
        code: 'OT010003',
        name: '',
        httpStatus: 400,
        message: '${resource} cannot be found or has been expire',
    },
    {
        code: 'OT010004',
        name: '',
        httpStatus: 400,
        message: '${resource} cannot be updated for some reason',
    },
    {
        code: 'OT010005',
        name: '',
        httpStatus: 400,
        message: "Retrieval of ${userid}'s wallet failed",
    },
    { code: 'OT010006', name: '', httpStatus: 400, message: 'Insufficient ${asset} Balance' },
    {
        code: 'OT010007',
        name: '',
        httpStatus: 400,
        message: '${resource} cannot be created for some reason.',
    },
    { code: 'OT010008', name: '', httpStatus: 400, message: 'Cannot hold specified amounts' },
    { code: 'OT010009', name: '', httpStatus: 400, message: 'Cannot hold specified amounts' },
    { code: 'OT010010', name: '', httpStatus: 400, message: 'Cannot create specified entries' },
    { code: 'OT010011', name: '', httpStatus: 400, message: 'Cannot create specified entries' },
    {
        code: 'OT010012',
        name: '',
        httpStatus: 400,
        message: 'Cannot reverse hold specified amounts',
    },
    {
        code: 'OT010013',
        name: '',
        httpStatus: 400,
        message: 'Cannot reverse hold specified amounts',
    },
    { code: 'OT010014', name: '', httpStatus: 400, message: 'Invalid quantity step : ${step}' },
    { code: 'OT010015', name: '', httpStatus: 400, message: 'Cannot correct balances' },
    { code: 'OT010016', name: '', httpStatus: 500, message: 'Asset unavailable' },
    { code: 'OT010017', name: '', httpStatus: 400, message: 'User not found' },
    { code: 'OT010018', name: '', httpStatus: 400, message: 'Invalid parameters' },
    { code: 'OT010019', name: '', httpStatus: 400, message: 'Minimum quantity limit reached' },
    { code: 'OT010020', name: '', httpStatus: 400, message: 'Maximum quantity limit reached' },
    {
        code: 'OT010021',
        name: '',
        httpStatus: 400,
        message: 'User not allowed to perform transaction',
    },
    { code: 'OT010022', name: '', httpStatus: 400, message: 'Withdrawal limit reached' },
    { code: 'OT010023', name: '', httpStatus: 400, message: 'Unsupported Transaction' },
    { code: 'OT010024', name: '', httpStatus: 400, message: 'Crypto Transfer not found' },
    { code: 'OT010025', name: '', httpStatus: 500, message: '${resource} is inaccessible' },
    { code: 'OT010026', name: '', httpStatus: 400, message: 'Malformed parameters' },
    {
        code: 'OT010027',
        name: '',
        httpStatus: 400,
        message: 'Order quantity is less than minimum required quantity',
    },
    {
        code: 'OT010028',
        name: '',
        httpStatus: 400,
        message: 'Order quantity is greater than maximum required quantity',
    },
    { code: 'OT010029', name: '', httpStatus: 400, message: 'Invalid Quantity Step' },
    { code: 'OT010030', name: '', httpStatus: 400, message: 'Invalid Price Step' },
    {
        code: 'OT010031',
        name: '',
        httpStatus: 400,
        message: 'Balance Transfer Approve Not Allowed',
    },
    { code: 'OT010032', name: '', httpStatus: 400, message: '${resource} rate limit exceeded' },
    { code: 'OT010033', name: '', httpStatus: 400, message: 'Missing parameter: ${param}' },
    { code: 'OT010034', name: '', httpStatus: 400, message: 'Invalid parameter: ${param}' },
    { code: 'OT010035', name: '', httpStatus: 400, message: 'Invalid ${field}' },
    { code: 'OT010036', name: '', httpStatus: 400, message: '${param} Request Failed' },
    { code: 'OT010037', name: '', httpStatus: 400, message: '${param} Verify Failed' },
    { code: 'OT010038', name: '', httpStatus: 400, message: '${param} Mismatch' },
    {
        code: 'OT010039',
        name: '',
        httpStatus: 400,
        message: 'Maximum retries reached. Account is now invalid.',
    },
    { code: 'OT010040', name: '', httpStatus: 500, message: 'Custody API failure encountered' },
    {
        code: 'OT010041',
        name: '',
        httpStatus: 500,
        message: 'Crypto withdrawal request not accepted by custody',
    },
    { code: 'OT010043', name: '', httpStatus: 400, message: 'Invalid Webhook Event' },
    { code: 'OT010044', name: '', httpStatus: 400, message: '${action} Not Allowed' },
    { code: 'OT010045', name: '', httpStatus: 500, message: 'Failed by Custody' },
    {
        code: 'OT010046',
        name: '',
        httpStatus: 500,
        message: 'Unable to fetch price for ${currencyPair}',
    },
    {
        code: 'Account has insufficient funds for the request',
        name: '',
        httpStatus: 400,
        message: 'There is insufficient funds in your account. Top-up your account and try again.',
    },
    {
        code: 'Amount exceeds the maximum for PAY-TO-ACCOUNT-NON-REAL-TIME method',
        name: '',
        httpStatus: 400,
        message: 'Could not process ubp/pesonet payment with amount greater than 10,000,000 PHP',
    },
    {
        code: 'Amount exceeds the maximum for PAY-TO-ACCOUNT-REAL-TIME method',
        name: '',
        httpStatus: 400,
        message: 'Could not process real-time payment with amount greater than 50,000 PHP',
    },
    {
        code: 'Identifier previously used. Identifier value should be unique for each request.',
        name: '',
        httpStatus: 400,
        message: 'Transaction identifier {{param.identity}} is already existing!',
    },
    { code: 'Internal server error', name: '', httpStatus: 500, message: 'Internal Server Error' },
    {
        code: 'Invalid amount',
        name: '',
        httpStatus: 400,
        message: 'amount is required and should be greater than 0. Until 2 decimal places',
    },
    {
        code: 'Invalid beneficiary DOB',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_dob is not valid, error: Please use correct format mm-dd-yyyy',
    },
    {
        code: 'Invalid beneficiary_bank_code',
        name: '',
        httpStatus: 400,
        message: 'Bank code {{param.beneficiary_bank_code}} is not valid',
    },
    {
        code: 'Invalid beneficiary_country',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_country is not valid, Accepted value are:  [List of countries]',
    },
    {
        code: 'Invalid beneficiary_nationality',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_nationality is not valid, Accepted value are:  [List of countries]',
    },
    {
        code: 'Invalid beneficiary_phone_number',
        name: '',
        httpStatus: 400,
        message:
            'beneficiary_phone_number is not valid, accept numeric only, no + symbol allowed or special characters',
    },
    {
        code: 'Invalid beneficiary_zip_code',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_zip_code is not valid',
    },
    { code: 'Invalid currency', name: '', httpStatus: 400, message: 'Currency only accept PHP' },
    {
        code: 'Invalid fee_type',
        name: '',
        httpStatus: 400,
        message: 'fee_type is not valid, Accepted value are: Sender, Beneficiary',
    },
    {
        code: 'Invalid method',
        name: '',
        httpStatus: 400,
        message: 'Method {{param.method}} is not supported!',
    },
    {
        code: 'Invalid purpose',
        name: '',
        httpStatus: 400,
        message:
            'purpose is not valid, Accepted value are: Business Expense/Employee Remittance, Business Transaction, Gift, Loan, Donation of Financial Aid, etc.',
    },
    {
        code: 'Invalid relationship_of_sender_to_beneficiary',
        name: '',
        httpStatus: 400,
        message:
            'relationship_of_sender_to_beneficiary is not valid, Accepted value are: Spouse/Partner, Family, Acquaintance, Colleague, Business, Myself',
    },
    {
        code: 'Invalid sender DOB',
        name: '',
        httpStatus: 400,
        message: 'sender_dob is not valid, error: Please use correct format mm-dd-yyyy',
    },
    {
        code: 'Invalid sender_country',
        name: '',
        httpStatus: 400,
        message: 'sender_country is not valid, Accepted value are:  [List of countries]',
    },
    {
        code: 'Invalid sender_country_origin',
        name: '',
        httpStatus: 400,
        message: 'sender_country_origin is not valid, Accepted value are:  [List of countries]',
    },
    {
        code: 'Invalid sender_email',
        name: '',
        httpStatus: 400,
        message: 'sender_email is not valid.',
    },
    {
        code: 'Invalid sender_nationality',
        name: '',
        httpStatus: 400,
        message: 'sender_nationality is not valid. Accepted value are:  [List of countries]',
    },
    {
        code: 'Invalid sender_phone_number',
        name: '',
        httpStatus: 400,
        message:
            'sender_phone_number is not valid, accept numeric only, no + symbol allowed or special characters',
    },
    {
        code: 'Invalid sender_zip_code',
        name: '',
        httpStatus: 400,
        message: 'sender_zip_code is not valid',
    },
    {
        code: 'Invalid sex',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_sex is not valid, Accepted value are: Male, Female',
    },
    {
        code: 'Invalid source_of_funds',
        name: '',
        httpStatus: 400,
        message:
            'source_of_funds is not valid, Accepted value are: Compensation, Sale/Income from Property, Business Income, Pension/Benefit from the Government, Gift/Donation, etc.',
    },
    {
        code: 'Maximum Limit (UBP)',
        name: '',
        httpStatus: 400,
        message: 'Could not process ubp/pesonet payment with amount greater than 10,000,000 PHP',
    },
    {
        code: 'Missing amount',
        name: '',
        httpStatus: 400,
        message: 'amount is required and should be greater than 0. Until 2 decimal places',
    },
    {
        code: 'Missing beneficiary_account_name',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_account_name is required',
    },
    {
        code: 'Missing beneficiary_account_number',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_account_number is required',
    },
    {
        code: 'Missing beneficiary_bank_code',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_bank_code is required',
    },
    {
        code: 'Missing beneficiary_first_name',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_first_name is required',
    },
    {
        code: 'Missing beneficiary_last_name',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_last_name is required',
    },
    {
        code: 'Missing beneficiary_middle_name',
        name: '',
        httpStatus: 400,
        message: 'beneficiary_middle_name is required',
    },
    { code: 'Missing currency', name: '', httpStatus: 400, message: 'Currency only accept PHP' },
    { code: 'Missing identifier', name: '', httpStatus: 400, message: 'identifier is required' },
    {
        code: 'Missing method',
        name: '',
        httpStatus: 400,
        message: 'Method {{param.method}} is not supported!',
    },
    { code: 'Missing purpose', name: '', httpStatus: 400, message: 'purpose is required' },
    {
        code: 'Missing relationship_of_sender_to_beneficiary',
        name: '',
        httpStatus: 400,
        message: 'relationship_of_sender_to_beneficiary is required',
    },
    {
        code: 'Missing sender_country_origin',
        name: '',
        httpStatus: 400,
        message: 'sender_country_origin is required',
    },
    {
        code: 'Missing sender_first_name',
        name: '',
        httpStatus: 400,
        message: 'sender_first_name is required',
    },
    {
        code: 'Missing sender_last_name',
        name: '',
        httpStatus: 400,
        message: 'sender_last_name is required',
    },
    {
        code: 'Missing sender_middle_name',
        name: '',
        httpStatus: 400,
        message: 'sender_middle_name is required',
    },
    {
        code: 'Missing source_of_funds',
        name: '',
        httpStatus: 400,
        message: 'source_of_funds is required',
    },
    {
        code: 'Required field for amount >= 50k PHP',
        name: '',
        httpStatus: 400,
        message:
            'Must provide either Sender Address Information or Sender National Identity Number or Sender Date Of Birth and Sender Place of Birth for amount >= 50,000 PHP',
    },
    { code: 'Unauthorized', name: '', httpStatus: 400, message: 'Invalid Session' },
];
