// Generated from PDAX page-data.json by generate-openapi.py — do not edit directly.
// Regenerate with: python3 src/lib/anchors/pdax/generate-openapi.py

export const SOURCES_OF_FUNDS = [
    "Compensation",
    "Sale/Income from Property",
    "Business Income",
    "Pension/Benefit from the Government",
    "Gift/Donation",
    "Sale/Income from Investment",
    "Inheritance/Insurance",
    "Others: <Free Text>",
] as const;
export type SourceOfFunds = (typeof SOURCES_OF_FUNDS)[number];

export const FEE_TYPES = [
    "Sender",
    "Beneficiary",
] as const;
export type FeeType = (typeof FEE_TYPES)[number];

export const SEX_VALUES = [
    "Male",
    "Female",
] as const;
export type Sex = (typeof SEX_VALUES)[number];

export const PURPOSES = [
    "Business Expense/Employee Remittance",
    "Business Transaction",
    "Gift",
    "Loan",
    "Donation of Financial Aid",
    "Investments/Savings",
    "Purchase of Goods",
    "Education and Training",
    "Travel Expense",
    "Family Support",
    "Legal Obligation",
] as const;
export type Purpose = (typeof PURPOSES)[number];

export const RELATIONSHIPS = [
    "Spouse/Partner",
    "Family",
    "Acquaintance",
    "Colleague",
    "Business",
    "Myself",
] as const;
export type RelationshipOfSenderToBeneficiary = (typeof RELATIONSHIPS)[number];

export const FIAT_IN_METHODS = [
    "grabpay_cashin",
    "dragonpay",
    "instapay_upay_cashin",
] as const;
export type FiatInMethod = (typeof FIAT_IN_METHODS)[number];

export const FIAT_OUT_METHODS = [
    "PAY-TO-ACCOUNT-REAL-TIME",
    "PAY-TO-ACCOUNT-NON-REAL-TIME",
] as const;
export type FiatOutMethod = (typeof FIAT_OUT_METHODS)[number];

export const COUNTRIES = [
    "Algeria",
    "Albania",
    "Antigua and Barbuda",
    "Armenia",
    "Angola",
    "Andorra",
    "Austria",
    "Bahamas",
    "Argentina",
    "Australia",
    "Azerbaijan",
    "Bahrain",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Chad",
    "Chile",
    "Colombia",
    "China",
    "Comoros",
    "Congo",
    "Croatia",
    "Costa Rica",
    "Cyprus",
    "Czech Republic",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "East Timor",
    "Egypt",
    "El Salvador",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Fiji",
    "France",
    "Gabon",
    "Gambia",
    "Germany",
    "Greece",
    "Ghana",
    "Grenada",
    "Guatemala",
    "Guinea-Bissau",
    "Guinea",
    "Guyana",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Malta",
    "Marshall Islands",
    "Mauritius",
    "Micronesia",
    "Monaco",
    "Montenegro",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "New Zealand",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "Sri Lanka",
    "Suriname",
    "Switzerland",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Trinidad and Tobago",
    "Turkey",
    "Tuvalu",
    "United Kingdom",
    "United Arab Emirates",
    "Uruguay",
    "Uzbekistan",
    "United States",
    "Vatican City",
    "Vietnam",
    "Zambia",
    "Vanuatu",
] as const;
export type Country = (typeof COUNTRIES)[number];

// Cash-in methods with their source wallet and rail mode. Mirrors
// FIAT_IN_METHODS but carries the metadata that the string union
// above can't express on its own.
export interface FiatInMethodInfo {
    method: FiatInMethod;
    sourceWallet: string;
    mode: string;
}
export const FIAT_IN_METHODS_INFO: readonly FiatInMethodInfo[] = [
    { method: "grabpay_cashin", sourceWallet: "Grab", mode: "Debit Pull" },
    { method: "dragonpay", sourceWallet: "All dragonpay supported banks", mode: "Debit Pull" },
    { method: "instapay_upay_cashin", sourceWallet: "All banks and e-wallets with QRPh enabled", mode: "Scan QRPh" },
];

// Crypto tokens supported by PDAX, filtered to Stellar network only.
// PDAX supports 47 additional tokens on other networks (Ethereum, Solana, Polygon, etc.) — see openapi.yaml for the full list.
export interface CryptoToken {
    symbol: string;
    network: string;
}
export const STELLAR_TOKENS: readonly CryptoToken[] = [
    { symbol: "USDCXLM", network: "Stellar" },
    { symbol: "XLM", network: "Stellar" },
];

// Bank codes used by /fiat/withdraw `beneficiary_bank_code`.
// Includes traditional banks and e-wallet rails.
export interface BankInfo {
    code: string;
    name: string;
    entityType: string;
}
export const BANK_CODES: readonly BankInfo[] = [
    { code: "BAUBPPH", name: "UnionBank", entityType: "Bank" },
    { code: "BAAIBPH", name: "Al-Amanah Islamic Investment Bank", entityType: "Bank" },
    { code: "BAALIPH", name: "Alipay", entityType: "Bank" },
    { code: "BAALLPH", name: "All Bank", entityType: "Bank" },
    { code: "BAAUBPH", name: "Asia United Bank", entityType: "Bank" },
    { code: "BAANZPH", name: "Australia and New Zealand Bank", entityType: "Bank" },
    { code: "BABDOPH", name: "BDO Unibank", entityType: "Bank" },
    { code: "BABDNPH", name: "BDO Network Bank", entityType: "Bank" },
    { code: "BABOTPH", name: "BPI", entityType: "Bank" },
    { code: "BABPIPH", name: "BPI Direct Banko", entityType: "Bank" },
    { code: "BABAKPH", name: "Bangko Kabayan", entityType: "Bank" },
    { code: "BABAMPH", name: "Banko Mabuhay", entityType: "Bank" },
    { code: "BABNSPH", name: "Bangko Nuestra Se\u00f1ora Del Pilar", entityType: "Bank" },
    { code: "BABKBPH", name: "Bangkok Bank", entityType: "Bank" },
    { code: "BABOAPH", name: "Bank Of America", entityType: "Bank" },
    { code: "BABCHPH", name: "Bank of China", entityType: "Bank" },
    { code: "BABOCPH", name: "Bank of Commerce", entityType: "Bank" },
    { code: "BABOFPH", name: "Bank of Florida", entityType: "Bank" },
    { code: "BABOMPH", name: "Bank of Makati", entityType: "Bank" },
    { code: "BACAMPH", name: "Camalig Bank", entityType: "Bank" },
    { code: "BACANPH", name: "Cantilan Bank", entityType: "Bank" },
    { code: "BACABPH", name: "Card Bank", entityType: "Bank" },
    { code: "BACASPH", name: "Card SME", entityType: "Bank" },
    { code: "BACIMPH", name: "CIMB Bank", entityType: "Bank" },
    { code: "BACTBPH", name: "CTBC Bank", entityType: "Bank" },
    { code: "BACLRPH", name: "Cebuana Lhuillier", entityType: "Bank" },
    { code: "BACHBPH", name: "China Bank", entityType: "Bank" },
    { code: "BACBSPH", name: "China Bank Savings", entityType: "Bank" },
    { code: "BACITPH", name: "Citibank", entityType: "Bank" },
    { code: "BACRBPH", name: "Community Rural Bank of Romblon", entityType: "Bank" },
    { code: "BACBBPH", name: "Country Builders Bank", entityType: "Bank" },
    { code: "BADEVPH", name: "Development Bank of Philippines", entityType: "Bank" },
    { code: "BADUNPH", name: "Dungganon Bank Inc.", entityType: "Bank" },
    { code: "BADEBPH", name: "Deutsche Bank", entityType: "Bank" },
    { code: "BADCDPH", name: "Dumaguete City Development Bank", entityType: "Bank" },
    { code: "BAEWBPH", name: "East West Bank", entityType: "Bank" },
    { code: "BAEWRPH", name: "East West Rural Bank", entityType: "Bank" },
    { code: "BAEQSPH", name: "Equicom", entityType: "Bank" },
    { code: "BAFCBPH", name: "First Consolidated Bank", entityType: "Bank" },
    { code: "BAGRBPH", name: "Guagua Rural Bank", entityType: "Bank" },
    { code: "BAGTBPH", name: "GoTyme", entityType: "Bank" },
    { code: "BAHSBPH", name: "HSBC Savings", entityType: "Bank" },
    { code: "BAHSSPH", name: "HSBC Savings", entityType: "Bank" },
    { code: "BAISLPH", name: "Isla Bank", entityType: "Bank" },
    { code: "BAICOPH", name: "Industrial & Commercial Bank of China", entityType: "Bank" },
    { code: "BAIBKPH", name: "Industrial Bank of Korea", entityType: "Bank" },
    { code: "BAINGPH", name: "ING Bank", entityType: "Bank" },
    { code: "BAIVBPH", name: "Innovative Bank", entityType: "Bank" },
    { code: "BAJPMPH", name: "JPMorgan Chase Bank", entityType: "Bank" },
    { code: "BAKEBPH", name: "KEB Hana Bank", entityType: "Bank" },
    { code: "BALABPH", name: "Landbank", entityType: "Bank" },
    { code: "BALSBPH", name: "Legazpi Savings Bank", entityType: "Bank" },
    { code: "BALDBPH", name: "Luzon Development Bank", entityType: "Bank" },
    { code: "BAICBPH", name: "Mega ICBC", entityType: "Bank" },
    { code: "BAMBSPH", name: "Malayan Bank", entityType: "Bank" },
    { code: "BAMAYPH", name: "Maybank", entityType: "Bank" },
    { code: "BAMCCPH", name: "MCCB", entityType: "Bank" },
    { code: "BAMBAPH", name: "Metrobank", entityType: "Bank" },
    { code: "BAMIZPH", name: "Mizuho Bank", entityType: "Bank" },
    { code: "BAMUFPH", name: "MUFG Bank", entityType: "Bank" },
    { code: "BANETPH", name: "Netbank", entityType: "Bank" },
    { code: "BAOMNPH", name: "Omnipay", entityType: "Bank" },
    { code: "BAPBOPH", name: "PBCom", entityType: "Bank" },
    { code: "BAPASPH", name: "Pacific Ace Savings Bank", entityType: "Bank" },
    { code: "BAPRBPH", name: "Partner Rural Bank", entityType: "Bank" },
    { code: "BAPBBPH", name: "Philippine Business Bank", entityType: "Bank" },
    { code: "BAPNBPH", name: "PNB", entityType: "Bank" },
    { code: "BAPBAPH", name: "PS Bank", entityType: "Bank" },
    { code: "BAPTCPH", name: "PhilTrust Bank", entityType: "Bank" },
    { code: "BAPVBPH", name: "Philippine Veterans Bank", entityType: "Bank" },
    { code: "BAPCBPH", name: "Producers Bank", entityType: "Bank" },
    { code: "BAPSBPH", name: "Producers Savings Bank", entityType: "Bank" },
    { code: "BAQBAPH", name: "Queen City Development Bank", entityType: "Bank" },
    { code: "BAQCRPH", name: "QCRB", entityType: "Bank" },
    { code: "BARANPH", name: "Rang-Ay Bank", entityType: "Bank" },
    { code: "BARCBPH", name: "RCBC", entityType: "Bank" },
    { code: "BAROBPH", name: "Robinsons Bank", entityType: "Bank" },
    { code: "BARBOPH", name: "Rural Bank of Guinobatan (Asenso)", entityType: "Bank" },
    { code: "BARBDPH", name: "Rural Bank of Digos", entityType: "Bank" },
    { code: "BARBMPH", name: "Rural Bank of Montalban", entityType: "Bank" },
    { code: "BASECPH", name: "Security Bank", entityType: "Bank" },
    { code: "BASEAPH", name: "Seabank", entityType: "Bank" },
    { code: "BASHBPH", name: "Shinhan Bank", entityType: "Bank" },
    { code: "BASCBPH", name: "Standard Chartered Bank", entityType: "Bank" },
    { code: "BASTAPH", name: "Starpay", entityType: "Bank" },
    { code: "BASBOPH", name: "Sterling Bank of Asia", entityType: "Bank" },
    { code: "BASMBPH", name: "Sumimoto Mitsui Banking", entityType: "Bank" },
    { code: "BASSBPH", name: "Sun Savings Bank", entityType: "Bank" },
    { code: "BATDBPH", name: "Tonik Digital Bank", entityType: "Bank" },
    { code: "BATYBPH", name: "Tong Yang Savings Bank", entityType: "Bank" },
    { code: "BAUCPPH", name: "UCPB Savings Bank", entityType: "Bank" },
    { code: "BAUCCPH", name: "United Coconut Planters Bank", entityType: "Bank" },
    { code: "BAUNOPH", name: "UNObank", entityType: "Bank" },
    { code: "BAUDLPH", name: "UnionDigital", entityType: "Bank" },
    { code: "BAUOVPH", name: "United Overseas Bank Phils.", entityType: "Bank" },
    { code: "BAWEBPH", name: "Wealth Bank", entityType: "Bank" },
    { code: "BAYSBPH", name: "Yuanta Savings Bank", entityType: "Bank" },
    { code: "BAMABPH", name: "Maya Bank", entityType: "Bank" },
    { code: "EWGXCPH", name: "GCash", entityType: "Ewallet" },
    { code: "EWCISPH", name: "Bayad", entityType: "Ewallet" },
    { code: "EWGRAPH", name: "GrabPay", entityType: "Ewallet" },
    { code: "EWLLFPH", name: "Lulu Money", entityType: "Ewallet" },
    { code: "EWPPPH", name: "PalawanPay", entityType: "Ewallet" },
    { code: "EWSPPPH", name: "ShopeePay", entityType: "Ewallet" },
    { code: "EWTACPH", name: "TayoCash", entityType: "Ewallet" },
    { code: "EWUSCPH", name: "USSC", entityType: "Ewallet" },
    { code: "EWJUCPH", name: "Juan Cash", entityType: "Ewallet" },
    { code: "EWPDXPH", name: "Philippine Digital Asset Exchange", entityType: "Ewallet" },
    { code: "EWPAYPH", name: "Maya Wallet", entityType: "Ewallet" },
];

// Global error codes from the PDAX API.
export interface ErrorInfo {
    code: string;
    name: string;
    httpStatus: number | null;
    message: string;
}
export const ERROR_CODES: readonly ErrorInfo[] = [
    { code: "PAP0400", name: "BadRequest", httpStatus: 400, message: "Bad request" },
    { code: "PAP0500", name: "InternalServerError", httpStatus: 500, message: "Internal Server Error" },
    { code: "PAP0503", name: "ServiceUnavailable", httpStatus: 503, message: "Service unavailable" },
    { code: "PAP0401", name: "Unauthorize", httpStatus: 401, message: "Unauthorize" },
];
